version: '3.8'

services: 
  app:
    container_name: app-front
    image: app-front
    build: 
      context: .
      target: development
    volumes: 
      - ./src:/app/src
    ports: 
      - 3000:3000 
    env_file:
      - .env 

networks:
    printgo_network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"